name: Runs tests
on: [push]
jobs:
    Explore-GitHub-Actions:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v2
            - run: npm install
            - run: npm test
            - run: npm run test:format
            - run: npm run test:lint
            - run: npm run test:types
