name: Runs tests
on: [push]
jobs:
    test:
        services:
            dynamodb:
                image: amazon/dynamodb-local
                ports:
                    - 8000:8000
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v2
            - run: npm ci
            - run: npm test
            - run: npm run test:format
            - run: npm run test:lint
            - run: npm run test:types
